name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.2.1
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.0.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  webview_flutter: ^3.0.4 # Use this instead of flutter_webview_plugin
  shared_preferences: ^2.0.9
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/openlayers_map.html
